from pydantic import BaseModel, Field
from typing import List, Dict, Any, Tuple, Union, Optional

# --- Experiment Related ---
class ExperimentMethodParams(BaseModel):
    method_name: str = Field(..., description="Name of the pipeline method, e.g., 'single_train'")
    params: Dict[str, Any] = Field(default_factory=dict, description="Parameters for the method")

class RunExperimentRequest(BaseModel):
    experiment_run_id: str = Field(..., description="ID generated by Java server, used for artifact paths")
    dataset_name: str = Field(..., description="Name of the dataset (e.g., 'CCSN', 'Swimcat-extend')")
    model_type: str = Field(..., description="Model type string (e.g., 'pvit', 'hyvit')")
    methods_sequence: List[ExperimentMethodParams] = Field(..., description="Sequence of methods to run")
    img_size_h: Optional[int] = None # Allow override
    img_size_w: Optional[int] = None
    save_model_default: Optional[bool] = True # For methods that support it
    offline_augmentation: Optional[bool] = False
    augmentation_strategy_override: Optional[str] = None # e.g., "PAPER_CCSN"
    # Add other executor/pipeline level params if you want Java to control them
    # e.g. force_flat, test_split_ratio_if_flat etc.

class ExperimentRunResponse(BaseModel):
    experiment_run_id: str
    message: str
    status: str = "SUBMITTED"

class ArtifactNode(BaseModel):
    name: str
    path: str # Full path relative to experiment_run_id folder for files, or relative to prefix for folders
    type: str # 'file' or 'folder'
    children: Optional[List['ArtifactNode']] = None # For folders

ArtifactNode.model_rebuild() # For self-referencing Pydantic model

# --- Prediction Related ---
class ImageIdFormatPair(BaseModel):
    image_id: Union[int, str] # SQL PK for the image
    image_format: str # e.g. "png", "jpg"

class ModelLoadDetails(BaseModel):
    # Information needed to reconstruct the model path for loading
    # These parts form the prefix: experiments/{dataset_name_of_model}/{model_type_of_model}/{experiment_run_id_of_model_producer}/
    dataset_name_of_model: str
    model_type_of_model: str
    experiment_run_id_of_model_producer: str
    # This is the path relative to the prefix above
    relative_model_path_in_experiment: str # e.g., "single_train_0/cnn_epoch5_val_loss0.123.pt"

class RunPredictionRequest(BaseModel):
    username: str
    image_id_format_pairs: List[ImageIdFormatPair]
    model_load_details: ModelLoadDetails
    experiment_run_id_of_model: str # ID of the experiment that *produced* the model (for result grouping)
    generate_lime: Optional[bool] = False
    lime_num_features: Optional[int] = 5
    lime_num_samples: Optional[int] = 100
    prob_plot_top_k: Optional[int] = -1

class SinglePredictionResult(BaseModel):
    image_id: Union[int, str]
    experiment_id: str # experiment_run_id_of_model
    predicted_class: str
    confidence: float

class PredictionRunResponse(BaseModel):
    predictions: List[SinglePredictionResult]
    message: str
